name: compiling-ceph

releases:
- name: ceph
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: compile
  instances: 1
  azs: [z1]
  jobs:
  - name: compile
    release: ceph
  vm_type: default
  stemcell: default
  networks:
  - name: default

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-90000
  update_watch_time: 1000-90000
